import { CCBLClock } from "./Clock";
import { CCBLContextState } from "./ContextState";
import { CCBLProgramObjectInterface, ChannelDescription, EmitterDescription, EventerDescription, HumanReadableEventAction, HumanReadableProgram, HumanReadableStateAction } from "./ProgramObjectInterface";
import { AllenType } from "./AllenInterface";
import { CCBLEnvironmentExecutionInterface } from "./ExecutionEnvironmentInterface";
import { CCBLEmitterValueInterface } from "./EmitterValueInterface";
import { ChannelInterface } from "./ChannelInterface";
import { CCBLEventInterface } from "./EventInterface";
import { CCBLContextEvent } from "./ContextEvent";
export declare class CCBLProgramObject implements CCBLProgramObjectInterface {
    private name;
    private clock;
    private localSubProgChannelsId;
    private localChannelsId;
    private localChannels;
    private inputChannelsId;
    private outputChannelsId;
    private localEmitters;
    private inputEmittersId;
    private outputEmittersId;
    private localEventers;
    private inputEventersId;
    private outputEventersId;
    private rootChannel;
    private rootContext;
    private environment;
    private localEventerContexts;
    private localStateContexts;
    private humanReadableDescription;
    private subPrograms;
    private parentProgram;
    constructor(name: string, clock: CCBLClock);
    dispose(): void;
    activate(v?: boolean): this;
    getEnvironment(): CCBLEnvironmentExecutionInterface;
    getRootChannel(): ChannelInterface<boolean>;
    getChannelDescription(id: string): ChannelDescription;
    getChannel(id: string, env?: CCBLEnvironmentExecutionInterface): ChannelInterface<any>;
    getEmitterDescription(id: string): EmitterDescription;
    getEmitter(id: string, env?: CCBLEnvironmentExecutionInterface): CCBLEmitterValueInterface<any>;
    getEventerDescription(id: string): EventerDescription;
    getEventer(id: string, env?: CCBLEnvironmentExecutionInterface): CCBLEventInterface<any>;
    getValue(id: string): any;
    getClock(): CCBLClock;
    appendEventActions(eventcontext: string | CCBLContextEvent, ...actions: HumanReadableEventAction[]): this;
    appendStateActions(stateContext: string | CCBLContextState<any, any>, ...actions: HumanReadableStateAction[]): this;
    appendSubProgram(programId: string, description: HumanReadableProgram): this;
    plugSubProgramAs(config: {
        programId: string;
        as: string;
        mapInputs: {
            [key: string]: string;
        };
        allen: AllenType;
        hostContextName: string | CCBLContextState<any, any>;
    }): this;
    toHumanReadableProgram(): HumanReadableProgram;
    getHumanReadableDescription(): HumanReadableProgram;
    loadHumanReadableProgram(descr: HumanReadableProgram, env: CCBLEnvironmentExecutionInterface, mapInputs: {
        [key: string]: string;
    }): this;
    private updateStructuralOrder;
    private createLocalEmitter;
    private loadContextOrProgram;
    private loadHumanReadableContext;
    private loadHumanReadableContextevent;
    private loadHumanReadableContextState;
    private getRootContext;
    private createLocalChannels;
    createLocalEventer(...eventers: EventerDescription[]): EventerDescription[];
    private getSubProgramIdentifiedBy;
}
