import { CCBLEnvironmentExecution } from "./ExecutionEnvironment";
import { CCBLTestClock } from "./Clock";
import { Channel } from "./Channel";
import { CCBLContextState } from "./ContextState";
import { CCBLEvent } from "./Event";
import { CCBLEmitterValue } from "./EmitterValue";
import { EnvDescr } from "./EnvProgTypes";
export declare let clock: CCBLTestClock;
export declare let envExo5: CCBLEnvironmentExecution;
declare type PLAY_STATE = "PLAY" | "PAUSE";
declare type FACE_CUBE = "undefined" | "Volume" | "Channel";
export declare let DomiCubeFace: CCBLEmitterValue<FACE_CUBE>;
export declare let DomiCubeRotation: CCBLEmitterValue<number>;
export declare let Phoning: CCBLEmitterValue<boolean>;
export declare let TV_isOn: Channel<boolean>;
export declare let TV_State: Channel<PLAY_STATE>;
export declare let TV_channel: Channel<number>;
export declare let TV_volume: Channel<number>;
export declare let chanVarBeta: Channel<number>;
export declare let TV_evtVolP: CCBLEvent<boolean>;
export declare let TV_evtVolM: CCBLEvent<boolean>;
export declare let TV_evtChanP: CCBLEvent<boolean>;
export declare let TV_evtChanM: CCBLEvent<boolean>;
export declare let ProgExo5State: CCBLEmitterValue<boolean>;
export declare let ProgExo5: CCBLContextState<any, any>;
export declare function initProgExo5Env(): void;
export declare let EnvDescr5: EnvDescr;
export {};
