import { CCBLEnvironmentExecution } from "./ExecutionEnvironment";
import { CCBLTestClock } from "./Clock";
import { Channel } from "./Channel";
import { CCBLContextState } from "./ContextState";
import { CCBLEmitterValue } from "./EmitterValue";
import { EnvDescr } from "./EnvProgTypes";
export declare let clock: CCBLTestClock;
export declare let envExo4: CCBLEnvironmentExecution;
declare type LAMP_STATE = "OFF" | "WHITE" | "ORANGE" | "GREEN";
export declare let LAMP_valueEmitter: CCBLEmitterValue<LAMP_STATE>;
export declare let LAMP_chan: Channel<LAMP_STATE>;
declare type LOCATION = "Alice's Home" | "Martin's Home" | "UNKNOWN";
declare type AVAILABILITY = "Available" | "Unavailable";
export declare let AliceLocation: CCBLEmitterValue<LOCATION>;
export declare let AliceAvailability: CCBLEmitterValue<AVAILABILITY>;
export declare let MartinLocation: CCBLEmitterValue<LOCATION>;
export declare let ProgExo4State: CCBLEmitterValue<boolean>;
export declare let EnvDescr4: EnvDescr;
export declare let ProgExo4: CCBLContextState<any, any>;
export declare function initProgExo4Env(): void;
export {};
